application: evolvechallenges
version: v2
runtime: python27
threadsafe: yes
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: app/favicon.ico
  upload: app/favicon\.ico

- url: /robots\.txt
  static_files: app/robots.txt
  upload: app/robots\.txt

- url: /(img|css|font|js|partials)/(.*)
  static_files: app/\1/\2
  upload: app/(img|css|font|js|partials)/(.*)

- url: /api/.*
  script: api.app

- url: /task/.*
  script: task.app
  login: admin

- url: /(.*)
  static_files: app/index.html
  upload: app/index.html

libraries:
- name: webapp2
  version: "2.5.2"
- name: django
  version: "1.4"