application: evolvechallenges
version: twitter
runtime: python27
threadsafe: yes
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: app/favicon.ico
  upload: app/favicon\.ico

- url: /robots\.txt
  static_files: app/robots.txt
  upload: app/robots\.txt

- url: /img
  static_dir: app/img

- url: /css
  static_dir: app/css

- url: /js
  static_dir: app/js

- url: /font
  static_dir: app/font
  mime_type: application/x-font-woff

- url: /partials
  static_dir: app/partials

- url: /api/.*
  script: api.app

- url: /task/.*
  script: task.app
  login: admin

- url: /(challenge/.*?|challenges|faq|donate|about)?
  static_files: app/index.html
  upload: app/index.html

- url: /.*
  static_files: app/errors/missing.html
  upload: app/errors/missing.html

libraries:
- name: webapp2
  version: "2.5.2"
- name: django
  version: "1.4"
- name: ssl
  version: latest

error_handlers:
  - file: app/errors/default.html
  
  - error_code: over_quota
    file: app/errors/quota.html

  - error_code: dos_api_denial
    file: app/errors/dos.html

  - error_code: timeout
    file: app/errors/timeout.html